global:
  scrape_interval: 15s  # 기본 스크래핑 주기

scrape_configs:
  # 1) Prometheus 자기 자신 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # 2) Node Exporter 모니터링
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # 3) cAdvisor 모니터링
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']